version: "1.0"
info:
  model: int-scaffold
packages:
- name: NewprojProject
  gitServerName: Dev8
  gitUrl: https://github.com/vijetadixit/NewprojProject
  gitUsername: vijetadixit
  gitBranch: test
- name: SIQA_OriginTest_OnPremAssets
  gitServerName: Dev8
  gitUrl: https://github.com/vijetadixit
  gitUsername: vijetadixit
  gitBranch: Test
